name: MLtrials
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  # - _openmp_mutex=4.5
  - attrs=19.3.0 
  - backcall=0.1.0 
  - bleach=3.1.0 
  - boost-cpp=1.70.0
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - cairo=1.16.0
  - certifi=2019.11.28   
  - cfitsio=3.470
  - click-plugins=1.1.1 
  # - cuda90=1.0
  - curl=7.65.3
  - cycler=0.10.0   
  - dbus=1.13.6
  - decorator=4.4.1 
  - defusedxml=0.6.0 
  - entrypoints=0.3
  - expat=2.2.9
  - fontconfig=2.13.1
  - freetype=2.10.0
  - freexl=1.0.5
  - gdal=2.4.1   
  - geos=3.7.2
  - geotiff=1.4.3   
  - gettext=0.19.8.1   
  - giflib=5.1.7   
  - glib=2.58.3   
  - gst-plugins-base=1.14.5   
  - gstreamer=1.14.5   
  - hdf4=4.2.13   
  - hdf5=1.10.4   
  - icu=58.2   
  - importlib_metadata=1.5.0   
  - inflect=4.0.0   
  - ipykernel=5.1.4   
  - ipython=7.12.0   
  - ipython_genutils=0.2.0   
  - ipywidgets=7.5.1 
  - jaraco.itertools=5.0.0 
  - jedi=0.16.0   
  - joblib=0.14.1 
  - jpeg=9c   
  - json-c=0.13.1   
  - jsonschema=3.2.0   
  - jupyter=1.0.0   
  - jupyter_client=5.3.4   
  - jupyter_console=6.0.0 
  - jupyter_core=4.6.1   
  - kealib=1.4.10   
  - kiwisolver=1.1.0   
  - krb5=1.16.4   
  - ld_impl_linux-64   
  - libblas=3.8.0   
  - libcblas=3.8.0   
  - libcurl=7.65.3   
  - libdap4=3.20.4   
  - libedit=3.1.20170329   
  - libffi=3.2.1   
  # - libgcc-ng=9.2.0   
  - libgdal=2.4.1   
  # - libgfortran-ng=7.3.0   
  # - libgomp=9.2.0   
  - libiconv=1.15   
  - libkml=1.3.0   
  - liblapack=3.8.0   
  - libnetcdf=4.6.2   
  - libopenblas=0.3.7   
  - libpng=1.6.37   
  - libpq=11.5   
  - libsodium=1.0.17   
  - libspatialindex=1.9.3   
  - libspatialite=4.3.0a   
  - libssh2=1.8.2   
  # - libstdcxx-ng=9.2.0   
  - libtiff=4.1.0   
  - libuuid=2.32.1   
  - libxcb=1.13   
  - libxml2=2.9.9   
  - lz4-c=1.8.3   
  - markupsafe=1.1.1   
  - matplotlib=3.1.1   
  - matplotlib-base=3.1.1   
  - mistune=0.8.4   
  - more-itertools=8.2.0 
  - natsort=6.0.0 
  - nbconvert=5.6.1   
  - nbformat=5.0.4 
  - ncurses=6.1   
  - notebook=6.0.3   
  - numpy=1.17.5   
  - openjpeg=2.3.1   
  - openssl=1.1.1d   
  - pandas=0.25.2   
  - pandoc=2.9.1.1=0
  - pandocfilters=1.4.2   
  - parso=0.6.0 
  - pcre=8.43   
  - pexpect=4.8.0   
  - pickleshare=0.7.5   
  - pip=20.0.2   
  - pixman=0.38.0   
  - poppler=0.67.0   
  - poppler-data=0.4.9
  - postgresql=11.5   
  - proj4=5.2.0   
  - prometheus_client=0.7.1 
  - prompt_toolkit=2.0.10 
  - pthread-stubs=0.4   
  - ptyprocess=0.6.0   
  - pygments=2.5.2 
  - pyparsing=2.4.6 
  - pyqt=5.9.2   
  - pyrsistent=0.15.7   
  - python=3.8   
  - python-dateutil=2.8.1 
  - pytz=2019.3 
  - pyzmq=18.1.1   
  - qt=5.9.7   
  - qtconsole=4.6.0 
  - readline=8.0   
  - rtree=0.8.3   
  - scikit-learn=0.21.3   
  - send2trash=1.5.0 
  - setuptools=45.1.0   
  - shapely=1.6.4   
  - sip=4.19.8
  - six=1.14.0   
  - sqlite=3.30.1   
  - terminado=0.8.3   
  - testpath=0.4.4 
  - tk=8.6.10   
  - tornado=6.0.3   
  - tqdm=4.36.1 
  - traitlets=4.3.3   
  - tzcode=2019a   
  - wcwidth=0.1.8 
  - webencodings=0.5.1   
  - wheel=0.34.2   
  - widgetsnbextension=3.5.1   
  - xerces-c=3.2.2   
  - xorg-kbproto=1.0.7   
  - xorg-libice=1.0.10   
  - xorg-libsm=1.2.3   
  - xorg-libx11=1.6.9   
  - xorg-libxau=1.0.9   
  - xorg-libxdmcp=1.1.3   
  - xorg-libxext=1.3.4   
  - xorg-libxrender=0.9.10   
  - xorg-renderproto=0.11.1   
  - xorg-xextproto=7.3.0   
  - xorg-xproto=7.0.31   
  - xz=5.2.4   
  - zeromq=4.3.2   
  - zipp=2.1.0 
  - zlib=1.2.11   
  - zstd=1.4.4   
  - pip:
    - absl-py==0.7.0
    - affine==2.3.0
    - albumentations==0.3.3
    - astor==0.7.1
    - chardet==3.0.4
    - click==7.0
    - cligj==0.5.0
    - community==1.0.0b1
    - fiona==1.8.8
    - flask==1.0.2
    - gast==0.2.2
    - geopandas==0.6.1
    - google-pasta==0.1.8
    - grpcio==1.19.0
    - h5py==2.9.0
    - idna==2.8
    - imageio==2.6.1
    - imgaug==0.2.6
    - itsdangerous==1.1.0
    - jinja2==2.10
    - keras-applications==1.0.8
    - keras-preprocessing==1.0.9
    - llvmlite==0.29.0
    - markdown==3.0.1
    - mercantile==1.1.2
    - mock==2.0.0
    - munch==2.3.2
    - networkx==2.2
    - numba==0.45.1
    - opencv-python==4.1.0.25
    - opencv-python-headless==4.1.1.26
    - opt-einsum==3.1.0
    - pbr==5.1.3
    - pillow==6.2.2
    - protobuf==3.11.1
    - pyemd==0.5.1
    - pyproj==2.4.0
    - pystac==0.3.1
    - python-louvain==0.13
    - pywavelets==1.1.1
    - pyyaml==5.1.2
    - rasterio==1.1.0
    - requests==2.22.0
    - rio-cogeo==1.1.5
    - scikit-image==0.16.2
    - scipy==1.2.1
    - sknw==0.13
    - snuggs==1.4.7
    - solaris==0.1.3
    - style==1.1.0
    - supermercado==0.0.5
    - tensorboard==1.15.0
    - tensorboard-logger==0.1.0
    - tensorboardx==2.0
    - tensorflow==1.15.0
    - tensorflow-estimator==1.15.1
    - termcolor==1.1.0
    - torch==1.3.0
    - torchlars==0.1.2
    - torchsummary==1.5.1
    - torchvision==0.4.1
    - umap-learn==0.3.10
    - update==0.0.1
    - urllib3==1.24.3
    - werkzeug==0.14.1
    - wrapt==1.12.0
# prefix: /home/lab/anaconda3/envs/pt120

